engines: 
  eslint:
    enabled: true
  nodesecurity:
    enabled: true
    duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
   paths:
   - "**.js"
   - "**.jsx"