version: 2.1

jobs:
  build:
    docker:
      - image: node/alpine-carbon
    steps:
      - checkout
      - run:
        name: Install deps
        command: npm i
      - run:
        name: Test app
        command: npm test
      - run:
        name: Codecov
        command: bash <(curl -s https://codecov.io/bash)
workflows:
  Build Workflow:
    jobs:
    - build
  version: 2